# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschol', '0003_journalunit_default_css_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='escholarticle',
            name='doi_result_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escholarticle',
            name='is_doi_registered',
            field=models.BooleanField(default=False),
        ),
    ]
