# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschol', '0004_auto_20220824_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='escholarticle',
            name='source_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
