# Generated by Django 3.2.20 on 2024-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschol', '0005_escholarticle_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='escholarticle',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
