# Generated by Django 3.2.18 on 2023-07-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschol', '0005_escholarticle_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalunit',
            name='ezid_template',
            field=models.CharField(choices=[('JC', 'Journal Content'), ('BC', 'Book Chapter')], default='JC', max_length=2),
        ),
    ]
