# Generated by Django 3.2.20 on 2024-07-19 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0062_auto_20240312_0922'),
        ('submission', '0076_alter_article_date_published'),
        ('eschol', '0006_escholarticle_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePublicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('result', models.TextField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePublicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('result', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('issue_pub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eschol.issuepublicationhistory')),
            ],
        ),
    ]
