# Generated by Django 3.2.20 on 2024-07-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eschol', '0007_articlepublicationhistory_issuepublicationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepublicationhistory',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='issuepublicationhistory',
            options={'ordering': ['-date']},
        ),
    ]
