# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-10 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalunit',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
