# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschol', '0002_auto_20220610_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalunit',
            name='default_css_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
